### ISSUE TITLE
Something Happened!!!

### ISSUE THREAD

**Issue by sixelavu** [MyUncleSam/TeamviewerExporter#2]
hi there, i love the tool. it's been working great exporting devices for me but recently i've been getting this error. i've checked my app permissions.

Connecting to teamviewer web api ...
Getting device list...
Getting groups list...

SOMETHING HAPPENED
System.NullReferenceException: Object reference not set to an instance of an object.
   at TeamviewerExporter.Program.Main(String[] args)
Press any enter to exit :-)

**Comment by MyUncleSam** [comment]
I tested it with my account and it is still working without problems. Maybe you changed something?

It seems like it cannot read the groups. Please check or recreate the script app entry inside teamviewer and make sure the correct permissions are set. I only have the german version, but maybe a screenshot helps (see below).

At the moment it is not possible to use the program without any teamviewer groups. I added now something to no make it possible not having any groups. But as I am using groups I am unable to test if it is working. All in all you can try it with the new version: https://github.com/MyUncleSam/TeamviewerExporter/releases/latest

![grafik](https://user-images.githubusercontent.com/12820919/100840946-e05e6500-3476-11eb-8fbc-0ae6f5b500ac.png)

**Comment by sixelavu** [comment]
thanks, i'll check.

**Comment by byteman-solutions** [comment]
I'm having the exact same issue. Here is the steps I've undertaken: (Version 1.0.1.0)

- Generate token with TeamViewer, ensuring both 'Group management' and 'Computers & Contacts' are set to Read/View
![image](https://user-images.githubusercontent.com/68819885/100927662-4ad7d980-3539-11eb-893a-3dbdfa6d60db.png)
- Download latest release zip
- Extract to downloads folder
- Edit config file, replacing token with previously generated token
- Run program (tested as user and 'Run as Administrator')

This is what I get back:
```
Connecting to teamviewer web api ...
Getting device list...
Getting groups list...
Got -1 entries and -1 groups.
Adding information to original entries...

SOMETHING HAPPENED
System.NullReferenceException: Object reference not set to an instance of an object.
   at TeamviewerExporter.Program.Main(String[] args)
Press any enter to exit :-)
```

My config file: (Token modified)
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <configSections>
        <sectionGroup name="applicationSettings" type="System.Configuration.ApplicationSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
            <section name="TeamviewerExporter.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
        </sectionGroup>
    </configSections>
    <applicationSettings>
        <TeamviewerExporter.Properties.Settings>
            <setting name="BaseUrl" serializeAs="String">
                <value>https://webapi.teamviewer.com</value>
            </setting>
            <setting name="DevicesUrlPart" serializeAs="String">
                <value>/api/v1/devices</value>
            </setting>
            <setting name="ImportDefaultPassword" serializeAs="String">
                <value />
            </setting>
            <setting name="GroupsUrlPart" serializeAs="String">
                <value>/api/v1/groups</value>
            </setting>
            <setting name="AuthorizationToken" serializeAs="String">
                <value>1102xxxx-LGFvi7GnM4AjjFxxxx</value>
            </setting>
        </TeamviewerExporter.Properties.Settings>
    </applicationSettings>
</configuration>
```

Update: I get the same issue in version 1.0.0.0, however the output was missing this line:
`Got -1 entries and -1 groups.`
This is the same output as sixelavu

**Comment by sixelavu** [comment]
hi, i just want to give an update. i have checked and recreated apps over and over to make sure i have correct settings for group and contacts, but i still get "Nothing Happened" on three machines (2 win7 and win10). thanks dev for checking.

**Comment by MyUncleSam** [comment]
In this version it prints out how much entries and groups it can read. This is the line `Got -1 entries and -1 groups.`. So it seems that it is unable to read anything from the teamviewer api using the information you provided.

I tested it with my teamviewer account and for me it is working fine (also with a new scripting app token).

But all in all I released a new version with some more logging. Maybe this could give us  some information.

**Comment by sixelavu** [comment]
Hi MyUncleSam,
Just tested new release and got:

Connecting to teamviewer web api ...
Getting device list...Error
Error Information: The underlying connection was closed: An unexpected error occurred on a send.
Getting groups list...Error
Error Information: The underlying connection was closed: An unexpected error occurred on a send.
Got -1 entries and -1 groups.
Adding information to original entries...

SOMETHING HAPPENED
System.NullReferenceException: Object reference not set to an instance of an object.
   at TeamviewerExporter.Program.Main(String[] args)
Press any enter to exit :-)

**Comment by MyUncleSam** [comment]
Hm seems like it worked yesterday for me, but today nothing seems to work anymore on my notebook.
I downloaded the test appliaction from teamviewer and it seems to have the same problem.

As the test application seems to have the same problem and I could not find why, I hope it is a temporary problem.

This small tool was built by me some years ago as I needed it. Now I no longer need it so I am not planning to invest much time in it.

**Comment by sixelavu** [comment]
cool, thanks for your time.

**Comment by MyUncleSam** [comment]
Ok seems like teamviewer changed the security protocols  of the webapi. I now switched to .Net 4.5 with TLS1.2 and it is working again for me. Please test the new version.

**Comment by sixelavu** [comment]
perfect. it's working with latest (1.0.3.0) version. thanks again for your time.
