### ISSUE TITLE
.Net 4.5 issue

### ISSUE THREAD

**Issue by SkyQuake1010** [MyUncleSam/TeamviewerExporter#3]
Hello,

Firstly, I'd like to thank you for this helpful script. However, I'm running into the following error.

"The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application." I'm running Windows 10. There isn't a Developer Pack for .Net 4.5. Have you seen this error before?

Thanks

**Comment by MyUncleSam** [comment]
This massage says that .Net Framework 4.5 is missing / not available. Please try to install .Net Framework 4.5:
https://www.microsoft.com/de-de/download/details.aspx?id=30653 (choose the correct language bevore downloading)

**Comment by MyUncleSam** [comment]
As I haven't heard anything I am closing this issue. All packages of .Net can be found here: https://dotnet.microsoft.com/en-us/download/visual-studio-sdks
